cache:
  paths:
    - .m2/repository/

stages:
  - build
  - test
  - image
  - deploy
build-job:
  stage: build
  image: maven:latest
  script:
    - mvn clean package -Dmaven.test.skip=true
  artifacts:
    paths:
      - target/

test-job:
  stage: test
  image: maven:latest
  script:
    - mvn test

build-image:
  stage: image
  image:
    name: gcr.io/kaniko-project/executor:v1.9.2-debug
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"

deploy-job:
  stage: deploy
  tags:
    - mouhamed-runner
  before_script:
    - echo "$CI_DEPLOY_PASSWORD" | docker login $CI_REGISTRY -u $CI_DEPLOY_USER --password-stdin
  script:
    - docker compose  -f ${CI_PROJECT_DIR}/docker-compose.yml up --force-recreate -d --remove-orphans
  environment:
    name: docker-local