image: maven:latest
#variables:
#  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
#  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
cache:
  paths:
    - .m2/repository/
    - target/
stages:
  - build
  - test
  - image
build-job:
  stage: build
  script:
    - mvn clean package

test-job:
  stage: test
  script:
    - mvn test

build-image:
  stage: image
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_PROJECT_NAME}:${CI_COMMIT_TAG}"
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH