image: maven:latest
#variables:
#  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
#  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
cache:
  paths:
    - .m2/repository/
    - target/
stages:
  - build
  - test
  - image
build-job:
  stage: build
  script:
    - mvn clean package

test-job:
  stage: test
  script:
    - mvn test

build-image:
  stage: image
  script:
    - apt-get install docker
    - docker build -t kata:bank-account .