image: maven:latest
#variables:
#  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
#  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
cache:
  paths:
    - .m2/repository/

stages:
  - build
  - test
  - image
build-job:
  stage: build
  image: maven:latest
  script:
    - mvn clean package -Dmaven.test.skip=true
  artifacts:
    paths:
      - target/

test-job:
  stage: test
  image: maven:latest
  script:
    - mvn test

build-image:
  stage: image
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
  tags:
    - mouhamed-runner