spring:
  datasource:
    platform:
      url: jdbc:h2:file:/data/bankAccount
      username: sa
      password: password
      driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console


  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.generate_statistics: false
      hibernate.format_sql: true
      hibernate.show_sql: true
      hibernate.cache.use_second_level_cache: false
      hibernate.dialact: org.hibernate.dialect.H2Dialect
    database: H2