spring:
  datasource:
    platform:
      url: jdbc:h2:mem:mydb
      username: sa
      password: sa
      driverClassName: org.h2.Driver
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  cache:
    types: redis
    cache-null-values: false
    time-to-live: 300000

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.generate_statistics: false
      hibernate.format_sql: true
      hibernate.show_sql: true
      hibernate.cache.use_second_level_cache: false
      hibernate.dialact: org.hibernate.dialect.H2Dialect
    database: H2
  data:
    redis:
      port: 26379
      password:
      sentinel:
        master: mymaster
        nodes: sentinel_1,sentinel_2,sentinel_3
      timeout: 600ms